name: Expo EAS Build Android

on:
  push:
    branches:
      - main
      - feature/deploy-monitoring

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del proyecto
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar EAS CLI
        run: npm install -g eas-cli

      - name: Autenticación en Expo
        run: eas login --token ${{ secrets.EXPO_TOKEN }}

      - name: Ejecutar build Android
        run: eas build --platform android --profile production --non-interactive
